# ==========================================
# Transformed Input Features for PINN
# ==========================================
columns:
  # Time Engineering
  time_cont: int64
  day_sin: float64
  day_cos: float64

  # Spatial Grid
  gps_lat: float64
  gps_lon: float64
  gps_alt: float64
  
  # Thermodynamic Drivers
  t_u: float64
  rh_u: float64
  wspd_u: float64
  albedo: float64
  
  # Targets & Metadata
  station_name: object
  t_surf: float64

# ==========================================
# Target Variable & Physics Flags
# ==========================================
target_column:
  name: t_surf